version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
   - "w3f/infrastructure"
  ignore:
   - dependency-name: "*"
     update-types: ["version-update:semver-major"]

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10    
  reviewers:
   - "w3f/infrastructure" 
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]