port: 3000
logLevel: info
evalIntervalMinutes: 5
targetDomains:
  cloudflare:
    enabled: false
    apiKey: secret
  manualList:  
  - example.com
virusTotal:
  apiKey: secret
ibmXforce:
  enabled: false
  apiKey: xxx
  apiPassword: xxx    